### ISSUE TITLE
int() argument must be a string, a bytes-like object or a real number, not 'Image'

### ISSUE THREAD

**Issue by yorkane** [ZHO-ZHO-ZHO/ComfyUI-UltraEdit-ZHO#10]
使用 样例：  V1.0 UltraEdit global & mask edit（local）【Zho】 .json 出错
求助~
![image](https://github.com/user-attachments/assets/8d8d9ce5-fc48-4ffc-a634-7b0ac35fb458)
100%|██████████| 50/50 [00:03<00:00, 15.47it/s]
!!! Exception during processing!!! int() argument must be a string, a bytes-like object or a real number, not 'Image'
Traceback (most recent call last):
  File "/home/aigc/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/aigc/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI-0246/utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "/home/aigc/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI-UltraEdit-ZHO/UltraEdit.py", line 184, in generate_image
    output_t = pil2tensor(output)
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI-UltraEdit-ZHO/UltraEdit.py", line 18, in pil2tensor
    return torch.from_numpy(np.array(image).astype(np.float32) / 255.0).unsqueeze(0)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Image'

**Comment by yorkane** [comment]
图片尺寸已经没有问题，就是在处理过程 torch.from_numpy(np.array(image).astype(np.float32) / 255.0).unsqueeze(0) 报错

**Comment by yorkane** [comment]
my bad, diffusion-dev version issue
