### ISSUE TITLE
一直在报这个错误，但是我的所有模型和config文件均已下载

### ISSUE THREAD

**Issue by DeepJackNotFound** [ZHO-ZHO-ZHO/ComfyUI-UltraEdit-ZHO#11]
C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\models\ultraedit\transformer\diffusion_pytorch_model.safetensors
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
`local_files_only` is True but no local configs were found for this checkpoint.
Attempting to download the necessary config files for this pipeline.###不知道在这行说的是什么config配置文件

!!! Exception during processing!!! An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
Traceback (most recent call last):
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000017C2AFAA850>, 'Connection to huggingface.co timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connectionpool.py", line 801, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\util\retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/runwayml/stable-diffusion-v1-5/revision/main (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017C2AFAA850>, 'Connection to huggingface.co timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 164, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\hf_api.py", line 2491, in repo_info
    return method(
           ^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\hf_api.py", line 2300, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\utils\_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\requests\adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/runwayml/stable-diffusion-v1-5/revision/main (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017C2AFAA850>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: b775378a-a6d7-4e69-a11b-ec6077dc5d97)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\research\SD\UltraEdit-main\diffusers\src\diffusers\loaders\single_file.py", line 409, in from_single_file
    cached_model_config_path = _download_diffusers_model_config_from_hub(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD\UltraEdit-main\diffusers\src\diffusers\loaders\single_file.py", line 250, in _download_diffusers_model_config_from_hub
    cached_model_path = snapshot_download(
                        ^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 236, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000017C2B8F7C50>, 'Connection to huggingface.co timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\connectionpool.py", line 801, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\urllib3\util\retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/runwayml/stable-diffusion-v1-5/revision/main (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017C2B8F7C50>, 'Connection to huggingface.co timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 164, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\hf_api.py", line 2491, in repo_info
    return method(
           ^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\hf_api.py", line 2300, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\utils\_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\requests\adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/runwayml/stable-diffusion-v1-5/revision/main (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017C2B8F7C50>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: e45b3d86-f976-43f3-bca0-42da142b59ff)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-UltraEdit-ZHO\UltraEdit.py", line 117, in load_model
    pipe = StableDiffusion3InstructPix2PixPipeline.from_single_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD\UltraEdit-main\diffusers\src\diffusers\loaders\single_file.py", line 432, in from_single_file
    cached_model_config_path = _download_diffusers_model_config_from_hub(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD\UltraEdit-main\diffusers\src\diffusers\loaders\single_file.py", line 250, in _download_diffusers_model_config_from_hub
    cached_model_path = snapshot_download(
                        ^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 236, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

**Comment by DeepJackNotFound** [comment]
换了一个HF的镜像源，文件下载下来了，但是貌似是.cache\huggingface\hub\models--runwayml--stable
-diffusion-v1-5。SD1.5的？
接下来报错了：
C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\models\ultraedit\transformer\diffusion_pytorch_model.safetensors
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:19<00:00,  4.89s/it]
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Fetching 11 files:   0%|                                                                                                                 | 0/11 [00:00<?, ?it/s]C
:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\huggingface_hub\file_download.py:157: UserWarning: `huggingface_hub` cache-system uses symlinks
 by default to efficiently store duplicated files but your machine does not support them in C:\Users\JackNotFound\.cache\huggingface\hub\models--runwayml--stable
-diffusion-v1-5. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Fetching 11 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.25it/s]
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]
C:\research\SD\UltraEdit-main\diffusers\src\diffusers\models\attention_processor.py:1581: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  hidden_states = F.scaled_dot_product_attention(
  0%|                                                                                                                                    | 0/50 [00:00<?, ?it/s]
!!! Exception during processing!!! The size of tensor a (55) must match the size of tensor b (54) at non-singleton dimension 3
Traceback (most recent call last):
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-UltraEdit-ZHO\UltraEdit.py", line 173, in generate_image
    output = pipe(
             ^^^^^
  File "C:\research\SD2024\comfyUI\ComfyUI-aki-v1.3\.ext\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD\UltraEdit-main\diffusers\src\diffusers\pipelines\stable_diffusion_3\pipeline_stable_diffusion_3_instructpix2pix.py", line 919, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, return_dict=False)[0]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\research\SD\UltraEdit-main\diffusers\src\diffusers\schedulers\scheduling_flow_match_euler_discrete.py", line 268, in step
    denoised = sample - model_output * sigma
               ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (55) must match the size of tensor b (54) at non-singleton dimension 3

**Comment by DeepJackNotFound** [comment]
很神奇。。。重启comfyUI后就能跑了。
issue closed
