### ISSUE TITLE
扩展加载失败

### ISSUE THREAD

**Issue by Sostay** [ZHO-ZHO-ZHO/ComfyUI-UltraEdit-ZHO#7]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI-UltraEdit-ZHO\__init__.py", line 1, in <module>
    from . import UltraEdit
  File "D:\ComfyUI\custom_nodes\ComfyUI-UltraEdit-ZHO\UltraEdit.py", line 5, in <module>
    from diffusers import StableDiffusion3InstructPix2PixPipeline, AutoencoderKL, FlowMatchEulerDiscreteScheduler, SD3Transformer2DModel
ImportError: cannot import name 'StableDiffusion3InstructPix2PixPipeline' from 'diffusers' (D:\ComfyUI\python\lib\site-packages\diffusers\__init__.py)

Cannot import D:\ComfyUI\custom_nodes\ComfyUI-UltraEdit-ZHO module for custom nodes: cannot import name 'StableDiffusion3InstructPix2PixPipeline' from 'diffusers' (D:\ComfyUI\python\lib\site-packages\diffusers\__init__.py)

**Comment by Sostay** [comment]
拼了老命都装不上这个特殊的 diffusers 版本……
![image](https://github.com/user-attachments/assets/8bcf4f8b-92b1-4d71-b630-7617a3782930)

**Comment by 428man** [comment]
怎么解决的？

**Comment by Sostay** [comment]
> 怎么解决的？

开全局代理 让它自动下载资源

**Comment by fwbc** [comment]
> > 怎么解决的？
> 
> 开全局代理 让它自动下载资源

你好，我也遇到这个问题了，可以详细说说你是怎么解决的吗
