### ISSUE TITLE
RuntimeError: The size of tensor a (55) must match the size of tensor b (54) at non-singleton dimension 3

### ISSUE THREAD

**Issue by c4fun** [ZHO-ZHO-ZHO/ComfyUI-UltraEdit-ZHO#9]
## 使用自己图片时报错

使用example不会报错，使用自己的图片报错。

使用图像的尺寸是 880 * 1176， 是4的倍数

## Log
```
got prompt
  0%|                                                                                                                              | 0/50 [00:00<?, ?it/s]
!!! Exception during processing!!! The size of tensor a (55) must match the size of tensor b (54) at non-singleton dimension 3
Traceback (most recent call last):
  File "/home/xxx/code/github.com/comfyanonymous/comfy-ultraedit-zho-individual/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/xxx/code/github.com/comfyanonymous/comfy-ultraedit-zho-individual/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/xxx/code/github.com/comfyanonymous/comfy-ultraedit-zho-individual/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/xxx/code/github.com/comfyanonymous/comfy-ultraedit-zho-individual/custom_nodes/ComfyUI-UltraEdit-ZHO/UltraEdit.py", line 173, in generate_image
    output = pipe(
  File "/opt/anaconda3/envs/python_310-cuda_11_8/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/python_310-cuda_11_8/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_instructpix2pix.py", line 919, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, return_dict=False)[0]
  File "/opt/anaconda3/envs/python_310-cuda_11_8/lib/python3.10/site-packages/diffusers/schedulers/scheduling_flow_match_euler_discrete.py", line 268, in step
    denoised = sample - model_output * sigma
RuntimeError: The size of tensor a (55) must match the size of tensor b (54) at non-singleton dimension 3

Prompt executed in 0.35 seconds
```

**Comment by DeepJackNotFound** [comment]
我只有512*512的图片可以使用，我放了一张1536*2048的图片就用不了
